### PR TITLE
Make it clear to the user that they must set helm-youtube-key

### PR DESCRIPTION
**Pull request by purcell**
In connection with https://github.com/melpa/melpa/pull/4352

### CODE REVIEW

**Comment by maximus12793** [comment]
@purcell added that info and fixed some of the docs. Appreciate the help!

**Comment by purcell** [comment]
But this was a merge request, not an issue - please consider re-opening it and merging it.

**Comment by maximus12793** [comment]
@purcell sorry about that

**Comment by purcell** [comment]
No worries. :-)

**Comment by maximus12793** [comment]
@purcell question. So i did notice just now that the function "helm-youtube-playvideo" is not actually being passed anything (the video-id is null). My lisp is very bad so I am not sure exactly how to debug this, since I was testing against the 400 error without the API key. Any idea? I can mess with it later tonight but perhaps you see the issue?

**Pull request merged**
